export const ADD_MOBILE_ORDER = "ADD_MOBILE_ORDER";
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const UPDATE_SINGLE_ORDER = "UPDATE_SINGLE_ORDER";
export const UPDATE_ORDER_LIST = "UPDATE_ORDER_LIST";
export const GET_SINGLE_ORDER = "GET_SINGLE_ORDER";
export const CLEAR_ORDER_DETAILS = "CLEAR_ORDER_DETAILS";
export const DELETE_ORDER = "DELETE_ORDER";